version: "3.9"
services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: books-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~