replicaCount: 1

image:
  repository: ghcr.io/arconsis/server_benchmarks
  name:
  pullPolicy: IfNotPresent
  tag:


db:
  host: "{{ .Release.Name }}-postgresql"
  name: books-db
  username: postgres


nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
     kubernetes.io/tls-acme: "true"
     cert-manager.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: "{{ .Release.Name }}.benchmarks.k8s.dev.arconsis.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "{{ .Release.Name }}-tls"
      hosts:
        - "{{ .Release.Name }}.benchmarks.k8s.dev.arconsis.com"

resources:
   limits:
     cpu: 1000m
     memory: 256Mi
   requests:
     cpu: 10m
     memory: 32Mi

