[package]
name = "bookstore-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
entity = { path = "../entity" }

[dependencies.sea-orm]
version = "0.11.2" # sea-orm version
features = [
    "debug-print",
    "runtime-actix-native-tls",
    "sqlx-postgres"
]

