version: "3.9"
services:
  bookstore:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: books-db
    depends_on:
      - postgres

  postgres:
    image: postgres:15.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: books-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~