version: "3.9"
services:
  bookstore:
    image: bookstore:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:secret@postgres:5432/books-db"
      HOST: 0.0.0.0
      PORT: 3000
    depends_on:
      - postgres

  postgres:
    image: postgres:15.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: books-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~