name: Quarkus Reactive Build & Deploy on k8s

on:
  push:
    branches:
      - '**'
    paths:
      - bookstore-quarkus-reactive/**


jobs:
  build:
    name: build & push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build & deploy quarkus
        uses: ./.github/actions/k8s/build-deploy-quarkus
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          kube-config: ${{ secrets.KUBECONFIG }}
          working-directory: ./bookstore-quarkus-reactive

      - name: deploy postgres
        uses: ./.github/actions/k8s/deploy-postgres
        with:
          release-name: bookstore-quarkus-reactive
          anti-affinity-value: bookstore-quarkus-reactive
          kube-config: ${{ secrets.KUBECONFIG }}